/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author sony
 */
public class Principal5 extends javax.swing.JFrame {

    /**
     * Creates new form Principal5
     */
   
   
    public Principal5() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNidentificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSactual = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIanual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNcuenta = new javax.swing.JTextField();
        cmdActualizarSaldo = new javax.swing.JButton();
        cmdIngresar = new javax.swing.JButton();
        txtIngresar = new javax.swing.JTextField();
        cmdRetirar = new javax.swing.JButton();
        txtRetirar = new javax.swing.JTextField();
        cmdGuardar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        jLabel1.setText("Cuenta ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 90, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("N° de Identificacion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));
        jPanel1.add(txtNidentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 80, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Saldo Actual");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtSactual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSactualActionPerformed(evt);
            }
        });
        jPanel1.add(txtSactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Interes Anual");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));
        jPanel1.add(txtIanual, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 80, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("N° de Cuenta");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        jPanel1.add(txtNcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, 30));

        cmdActualizarSaldo.setText("Actualizar Saldo");
        cmdActualizarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarSaldoActionPerformed(evt);
            }
        });
        jPanel1.add(cmdActualizarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        cmdIngresar.setText("Ingresar");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));
        jPanel1.add(txtIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 80, 30));

        cmdRetirar.setText("Retirar");
        cmdRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        txtRetirar.setText("jTextField1");
        jPanel1.add(txtRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 80, 30));

        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        cmdLimpiar.setText("Limpiar");
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSactualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSactualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSactualActionPerformed

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed
    
    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
     if (txtNcuenta.getText().isEmpty()) {
     getToolkit().beep();
     JOptionPane.showMessageDialog(this, "Digite el Número de cuenta", "error", JOptionPane.ERROR_MESSAGE);
     txtNcuenta.requestFocusInWindow();
     }
     else if (txtNidentificacion.getText().isEmpty()) {
     getToolkit().beep();
     JOptionPane.showMessageDialog(this, "Digite el Número de Identificacion", "error", JOptionPane.ERROR_MESSAGE);
     txtNidentificacion.requestFocusInWindow();
     }
     else if (txtSactual.getText().isEmpty()) {
     getToolkit().beep();
     JOptionPane.showMessageDialog(this, "Digite el Saldo Actual", "error", JOptionPane.ERROR_MESSAGE);
     txtSactual.requestFocusInWindow();
     }
     else if (txtIanual.getText().isEmpty()) {
     getToolkit().beep();
     JOptionPane.showMessageDialog(this, "Digite el Interes Anual", "error", JOptionPane.ERROR_MESSAGE);
     txtIanual.requestFocusInWindow();
     }
     else {
            JOptionPane.showMessageDialog(this, "Datos guardados exitosamente");
           /* txtNcuenta.setEditable(false);
            txtNidentificacion.setEditable(false);
            txtSactual.setEditable(false);
            txtIanual.setEditable(false);
            cmdGuardar.setEnabled(false);
            
            
            cmdLimpiar.setEnabled(true);*/
        }      
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdActualizarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarSaldoActionPerformed
     Cuenta c;
    int ncuenta,nid,sactual,intanual; 
    double act;
   
    ncuenta = Integer.parseInt((txtNcuenta).getText());
    nid = Integer.parseInt((txtNidentificacion).getText());
    sactual = Integer.parseInt((txtSactual).getText());
    intanual = Integer.parseInt((txtIanual).getText());
    
    c = new Cuenta(ncuenta, nid, sactual, intanual);
    
    
    act = c.ActualizarSaldo();
                txtResultado.setText("" + act);
                JOptionPane.showMessageDialog(this, "Saldo actualizado correctamente");
        
        
    }//GEN-LAST:event_cmdActualizarSaldoActionPerformed

    private void cmdRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetirarActionPerformed
   /* long aux;
        long ns;
        int res;
        if (c.getSactual() == 0) {
            JOptionPane.showMessageDialog(this, "Usted no tiene saldo");
        }
        aux = Long.parseLong(JOptionPane.showInputDialog(this, "Digite el total a retirar"));
        while (aux > c.getSactual()) {
            aux = Long.parseLong(JOptionPane.showInputDialog(this, "Debe tener una cantidad validad para retirar, ingrese su saldo nuevamente"));
        }
        res = JOptionPane.showConfirmDialog(this, "¿Seguro que desea retirar esta cantidad?: " + aux, "Pregunta", JOptionPane.YES_NO_OPTION);
        if (res == 0) {
        //    ns = c.getSactual() - aux;
        //    c.setSactual(ns);
            txtResultado.append("Se ha retirado una nueva cantidad, su saldo actual es: " + c.getSactual() + "\n");

        } else {
            txtResultado.append("No se ha registrado ningún cambio su saldo es: " + c.getSactual() + "\n");
            cmdGuardar.setEnabled(false);
            cmdIngresar.setEnabled(true);
            cmdActualizarSaldo.setEnabled(true);
            cmdRetirar.setEnabled(true);
            cmdLimpiar.setEnabled(true);
            cmdMostrar.setEnabled(true);
        }*/
    }//GEN-LAST:event_cmdRetirarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdActualizarSaldo;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIanual;
    private javax.swing.JTextField txtIngresar;
    private javax.swing.JTextField txtNcuenta;
    private javax.swing.JTextField txtNidentificacion;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtRetirar;
    private javax.swing.JTextField txtSactual;
    // End of variables declaration//GEN-END:variables
}
