/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Excepciones.NoCeroException;
import Excepciones.NoFondosException;
import Excepciones.NoNegativoException;
import clases.Cuenta;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author sony
 */
public class Principal5 extends javax.swing.JFrame {

    /**
     * Creates new form Principal5
     */
    Cuenta c;

    public Principal5() {
        initComponents();
        cmdGuardar.setEnabled(true);
        cmdIngresar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdActualizarSaldo.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdLimpiar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmdActualizarSaldo = new javax.swing.JButton();
        cmdIngresar = new javax.swing.JButton();
        txtIngresar = new javax.swing.JTextField();
        cmdRetirar = new javax.swing.JButton();
        txtRetirar = new javax.swing.JTextField();
        cmdGuardar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        txtNcuenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSactual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNidentificacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIanual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        jLabel1.setText("Cuenta ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 90, -1));

        cmdActualizarSaldo.setText("Actualizar Saldo");
        cmdActualizarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarSaldoActionPerformed(evt);
            }
        });
        jPanel1.add(cmdActualizarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        cmdIngresar.setText("Ingresar");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 110, -1));

        txtIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIngresarKeyTyped(evt);
            }
        });
        jPanel1.add(txtIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 80, 30));

        cmdRetirar.setText("Retirar");
        cmdRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 110, -1));

        txtRetirar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRetirarKeyTyped(evt);
            }
        });
        jPanel1.add(txtRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 80, 30));

        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 110, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 110, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 110, -1));

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 220, 170));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNcuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNcuentaKeyTyped(evt);
            }
        });
        jPanel2.add(txtNcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("N° de Cuenta");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtSactual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSactualActionPerformed(evt);
            }
        });
        txtSactual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSactualKeyTyped(evt);
            }
        });
        jPanel2.add(txtSactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Saldo Actual");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("N° de Identificacion");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        txtNidentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNidentificacionKeyTyped(evt);
            }
        });
        jPanel2.add(txtNidentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 80, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Interes Anual");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        txtIanual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIanualKeyTyped(evt);
            }
        });
        jPanel2.add(txtIanual, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 80, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 260, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSactualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSactualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSactualActionPerformed

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed
        double ingreso;

        if (txtIngresar.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Digite el Monto a Ingresar", "Error", JOptionPane.ERROR_MESSAGE);
            txtIngresar.requestFocusInWindow();
        } else {
            ingreso = Double.parseDouble((txtIngresar).getText());

            try {
                c.ingresar(ingreso);
            } catch (NoNegativoException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (NoCeroException ex) {
               JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
            txtIngresar.setText("");
            txtRetirar.setText("");
            DecimalFormat df = new DecimalFormat("0.00");
            try {
                txtResultado.append("Saldo actual: " + (df.format(c.getSaldo_actual())) + "\n");
            } catch (NoNegativoException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

            cmdGuardar.setEnabled(false);
            cmdIngresar.setEnabled(true);
            cmdRetirar.setEnabled(true);
            cmdActualizarSaldo.setEnabled(true);
            cmdMostrar.setEnabled(true);
            cmdLimpiar.setEnabled(true);
        }
    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        long ncuenta, id;
        double saldoa;

        if (txtNcuenta.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Digite el Número de cuenta", "Error", JOptionPane.ERROR_MESSAGE);
            txtNcuenta.requestFocusInWindow();
        } else if (txtNidentificacion.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Digite el Número de Identificacion", "Error", JOptionPane.ERROR_MESSAGE);
            txtNidentificacion.requestFocusInWindow();
        } else if (txtSactual.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Digite el Saldo Actual", "Error", JOptionPane.ERROR_MESSAGE);
            txtSactual.requestFocusInWindow();
        } else if (txtIanual.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Digite el Interes Anual", "Error", JOptionPane.ERROR_MESSAGE);
            txtIanual.requestFocusInWindow();
        } else {

            ncuenta = Long.parseLong(txtNcuenta.getText());
            id = Long.parseLong(txtNidentificacion.getText());
            saldoa = Double.parseDouble(txtSactual.getText());

            try {
                c = new Cuenta(ncuenta, id, saldoa);
            } catch (NoNegativoException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            } catch (NoCeroException ex) {
               JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
            JOptionPane.showMessageDialog(this, "Datos guardados exitosamente");

            cmdGuardar.setEnabled(false);
            cmdIngresar.setEnabled(true);
            cmdRetirar.setEnabled(true);
            cmdActualizarSaldo.setEnabled(true);
            cmdMostrar.setEnabled(true);
            cmdLimpiar.setEnabled(true);
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdActualizarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarSaldoActionPerformed
        double ian;

        ian = Double.parseDouble((txtIanual).getText());

        try {
            c.actualizar_saldo(ian);
        } catch (NoNegativoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        txtIngresar.setText("");
        txtRetirar.setText("");
        DecimalFormat df = new DecimalFormat("0.00");
        try {
            txtResultado.append("Saldo actual: " + (df.format(c.getSaldo_actual())) + "\n");
        } catch (NoNegativoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }

        cmdGuardar.setEnabled(false);
        cmdIngresar.setEnabled(true);
        cmdRetirar.setEnabled(true);
        cmdActualizarSaldo.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdActualizarSaldoActionPerformed

    private void cmdRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetirarActionPerformed
        double egreso, aux, aux2 = 0;

        if (txtRetirar.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Digite el Monto a Retirar", "Error", JOptionPane.ERROR_MESSAGE);
            txtRetirar.requestFocusInWindow();
        } else {
            aux = Double.parseDouble((txtRetirar).getText());
            try {
                aux2 = c.getSaldo_actual();
            } catch (NoNegativoException ex) {
               JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }

            if (aux > aux2) {
                aux = Double.parseDouble((txtRetirar).getText());
                try {
                    aux2 = c.getSaldo_actual();
                } catch (NoNegativoException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                }
                getToolkit().beep();
                JOptionPane.showMessageDialog(this, "No puede retirar esta cantidad", "Error", JOptionPane.ERROR_MESSAGE);
                txtRetirar.selectAll();
                txtRetirar.requestFocusInWindow();
            } else {
                egreso = Double.parseDouble((txtRetirar).getText());

                try {
                    c.retira(egreso);
                } catch (NoNegativoException ex) {
                   JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                } catch (NoCeroException ex) {
                   JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                } catch (NoFondosException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                }
                txtIngresar.setText("");
                txtRetirar.setText("");
                DecimalFormat df = new DecimalFormat("0.00");
                try {
                    txtResultado.append("Saldo actual: " + (df.format(c.getSaldo_actual())) + "\n");
                } catch (NoNegativoException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                }

                cmdGuardar.setEnabled(false);
                cmdIngresar.setEnabled(true);
                cmdRetirar.setEnabled(true);
                cmdActualizarSaldo.setEnabled(true);
                cmdMostrar.setEnabled(true);
                cmdLimpiar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_cmdRetirarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        try {
            c.mostrar();
        } catch (NoNegativoException ex) {
           JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        try {
            txtResultado.append(c.mostrar() + "\n");
        } catch (NoNegativoException ex) {
           JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }

        cmdGuardar.setEnabled(false);
        cmdIngresar.setEnabled(true);
        cmdRetirar.setEnabled(true);
        cmdActualizarSaldo.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtNcuenta.setText("");
        txtNidentificacion.setText("");
        txtSactual.setText("");
        txtIanual.setText("");
        txtIngresar.setText("");
        txtRetirar.setText("");
        txtResultado.setText("");
        txtNcuenta.requestFocusInWindow();

        cmdGuardar.setEnabled(true);
        cmdIngresar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdActualizarSaldo.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void txtNcuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNcuentaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNcuentaKeyTyped

    private void txtNidentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNidentificacionKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNidentificacionKeyTyped

    private void txtSactualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSactualKeyTyped
        /* char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }*/
    }//GEN-LAST:event_txtSactualKeyTyped

    private void txtIanualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIanualKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtIanualKeyTyped

    private void txtIngresarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresarKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtIngresarKeyTyped

    private void txtRetirarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetirarKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtRetirarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdActualizarSaldo;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIanual;
    private javax.swing.JTextField txtIngresar;
    private javax.swing.JTextField txtNcuenta;
    private javax.swing.JTextField txtNidentificacion;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtRetirar;
    private javax.swing.JTextField txtSactual;
    // End of variables declaration//GEN-END:variables
}
